<html>
    <head>
        <meta charset="utf-8">
        <title>js 实现一个Promise</title>
    </head>
    <body>
        <script>
            try {
                module.exports = Promise
            } catch (e) {}

            function Promise(executor) {
                var self = this

                self.status = 'pending'  // Promise当前的状态
                // Promise resolve时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
                self.onResolvedCallback = []
                // Promise reject时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
                self.onRejectedCallback = []

                function resolve(value) {
                    if (value instanceof Promise) {
                      return value.then(resolve, reject)
                    }
                    setTimeout(function() { // 异步执行所有的回调函数
                      if (self.status === 'pending') {
                        self.status = 'resolved'
                        self.data = value
                        for (var i = 0; i < self.onResolvedCallback.length; i++) {
                          self.onResolvedCallback[i](value)
                        }
                      }
                    })
                }

                function reject(reason) {
                    setTimeout(function() { // 异步执行所有的回调函数
                      if (self.status === 'pending') {
                        self.status = 'rejected'
                        self.data = reason
                        for (var i = 0; i < self.onRejectedCallback.length; i++) {
                          self.onRejectedCallback[i](reason)
                        }
                      }
                    })
                }
                // 考虑到执行executor的过程中有可能出错，所以我们用try/catch块给包起来，
                // 并且在出错后以catch到的值reject掉这个Promise
                try {
                    // 执行executor并传入相应的参数
                    executor(resolve, reject)
                } catch (reason) {
                    reject(reason)
                }
            }

            // resolvePromise函数即为根据x的值来决定promise2的状态的函数
            function resolvePromise(promise2, x, resolve, reject) {
                var then
                var thenCalledOrThrow = false

                if (promise2 === x) {
                    return reject(new TypeError('Chaining cycle detected for promise!'))
                }

                if (x instanceof Promise) {
                    // 如果x的状态还没有确定，那么它是有可能被一个thenable决定最终状态和值的
                    // 所以这里需要做一下处理，而不能一概的以为它会被一个“正常”的值resolve
                    if (x.status === 'pending') { //because x could resolved by a Promise Object
                      x.then(function(v) {
                        resolvePromise(promise2, v, resolve, reject)
                      }, reject)
                    } else { //but if it is resolved, it will never resolved by a Promise Object but a static value;
                        // 但如果这个Promise的状态已经确定了，那么它肯定有一个“正常”的值，而不是一个thenable，所以这里直接取它的状态
                      x.then(resolve, reject)
                    }
                    return
                }

                if ((x !== null) && ((typeof x === 'object') || (typeof x === 'function'))) {
                    try {
                      then = x.then //because x.then could be a getter
                      if (typeof then === 'function') {
                        then.call(x, function rs(y) {
                          if (thenCalledOrThrow) return
                          thenCalledOrThrow = true
                          return resolvePromise(promise2, y, resolve, reject)
                        }, function rj(r) {
                          if (thenCalledOrThrow) return
                          thenCalledOrThrow = true
                          return reject(r)
                        })
                      } else {
                        resolve(x)
                      }
                    } catch (e) {
                      if (thenCalledOrThrow) return
                      thenCalledOrThrow = true
                      return reject(e)
                    }
                } else {
                    resolve(x)
                }
            }

            Promise.prototype.then = function(onResolved, onRejected) {
                var self = this
                var promise2
                // 根据标准，如果then的参数不是function，则我们需要忽略它，此处以如下方式处理
                // 把then的实参留空且让值可以穿透到后面
                onResolved = typeof onResolved === 'function' ? onResolved : function(v) {
                    return v
                }
                onRejected = typeof onRejected === 'function' ? onRejected : function(r) {
                    throw r
                }

                if (self.status === 'resolved') {
                    // 如果promise1(此处即为this/self)的状态已经确定并且是resolved，我们调用onResolved
                    // 因为考虑到有可能throw，所以我们将其包在try/catch块里
                    return promise2 = new Promise(function(resolve, reject) {
                      setTimeout(function() { // 异步执行onResolved
                        try {
                          var x = onResolved(self.data)
                          resolvePromise(promise2, x, resolve, reject)
                        } catch (reason) {
                          reject(reason)
                        }
                      })
                    })
                }

                if (self.status === 'rejected') {
                    return promise2 = new Promise(function(resolve, reject) {
                      setTimeout(function() { // 异步执行onRejected
                        try {
                          var x = onRejected(self.data)
                          resolvePromise(promise2, x, resolve, reject)
                        } catch (reason) {
                          reject(reason)
                        }
                      })
                    })
                }

                if (self.status === 'pending') {
                    // 这里之所以没有异步执行，是因为这些函数必然会被resolve或reject调用，
                    // resolve或reject函数里的内容已是异步执行，构造函数里的定义
                    return promise2 = new Promise(function(resolve, reject) {
                      self.onResolvedCallback.push(function(value) {
                        try {
                          var x = onResolved(value)
                          resolvePromise(promise2, x, resolve, reject)
                        } catch (r) {
                          reject(r)
                        }
                      })

                      self.onRejectedCallback.push(function(reason) {
                          try {
                            var x = onRejected(reason)
                            resolvePromise(promise2, x, resolve, reject)
                          } catch (r) {
                            reject(r)
                          }
                        })
                    })
                }
            }

            Promise.prototype.catch = function(onRejected) {
                return this.then(null, onRejected)
            }

            Promise.deferred = Promise.defer = function() {
                var dfd = {}
                dfd.promise = new Promise(function(resolve, reject) {
                    dfd.resolve = resolve
                    dfd.reject = reject
                })
                return dfd
            }
            new Promise(function(resolve,reject){

            })
        </script>
    </body>
</html>
